// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rewind.Data;

namespace Rewind.Migrations
{
    [DbContext(typeof(RewindDB))]
    [Migration("20210615230415_RestricoesExtra")]
    partial class RestricoesExtra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rewind.Models.Comentarios", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estrelas")
                        .HasColumnType("int");

                    b.Property<int>("SeriesID")
                        .HasColumnType("int");

                    b.Property<int>("UtilizadoresID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SeriesID");

                    b.HasIndex("UtilizadoresID");

                    b.ToTable("Comentarios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Comentario = "bom",
                            Data = new DateTime(2021, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "visivel",
                            Estrelas = 0,
                            SeriesID = 1,
                            UtilizadoresID = 1
                        },
                        new
                        {
                            ID = 2,
                            Comentario = "mau",
                            Data = new DateTime(2021, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "invisivel",
                            Estrelas = 0,
                            SeriesID = 2,
                            UtilizadoresID = 2
                        },
                        new
                        {
                            ID = 3,
                            Comentario = "mais ou menos",
                            Data = new DateTime(2020, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "visivel",
                            Estrelas = 0,
                            SeriesID = 3,
                            UtilizadoresID = 3
                        });
                });

            modelBuilder.Entity("Rewind.Models.Estudios", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Estudio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Estudios");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Estudio = "ABC",
                            Pais = "Portugal"
                        },
                        new
                        {
                            ID = 2,
                            Estudio = "ACR",
                            Pais = "França"
                        },
                        new
                        {
                            ID = 3,
                            Estudio = "TCB",
                            Pais = "Espanha"
                        });
                });

            modelBuilder.Entity("Rewind.Models.Series", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Episodios")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstudioID")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EstudioID");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ano = 2004,
                            Data = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Episodios = 1,
                            Estado = "continuando",
                            EstudioID = 1,
                            Imagem = "a.jpg",
                            Sinopse = "Morbi laoreet neque",
                            Titulo = "Lorem ipsum"
                        },
                        new
                        {
                            ID = 2,
                            Ano = 2005,
                            Data = new DateTime(2021, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Episodios = 4,
                            Estado = "terminado",
                            EstudioID = 2,
                            Imagem = "b.jpg",
                            Sinopse = "ut erat gravida",
                            Titulo = "dolor sit amet"
                        },
                        new
                        {
                            ID = 3,
                            Ano = 2012,
                            Data = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Episodios = 2,
                            Estado = "continuando",
                            EstudioID = 3,
                            Imagem = "c.jpg",
                            Sinopse = "Integer mattis lorem et lorem",
                            Titulo = "consectetur adipiscing elit"
                        });
                });

            modelBuilder.Entity("Rewind.Models.Utilizadores", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Utilizador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("Utilizadores");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "a@aa",
                            Utilizador = "admin"
                        },
                        new
                        {
                            ID = 2,
                            Email = "b@bb",
                            Utilizador = "antonio"
                        },
                        new
                        {
                            ID = 3,
                            Email = "c@cc",
                            Utilizador = "tomas"
                        });
                });

            modelBuilder.Entity("Rewind.Models.Comentarios", b =>
                {
                    b.HasOne("Rewind.Models.Series", "Serie")
                        .WithMany("ListaDeComentarios")
                        .HasForeignKey("SeriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rewind.Models.Utilizadores", "Utilizador")
                        .WithMany("ListaDeComentarios")
                        .HasForeignKey("UtilizadoresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("Rewind.Models.Series", b =>
                {
                    b.HasOne("Rewind.Models.Estudios", "Estudio")
                        .WithMany("ListaDeSeries")
                        .HasForeignKey("EstudioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudio");
                });

            modelBuilder.Entity("Rewind.Models.Estudios", b =>
                {
                    b.Navigation("ListaDeSeries");
                });

            modelBuilder.Entity("Rewind.Models.Series", b =>
                {
                    b.Navigation("ListaDeComentarios");
                });

            modelBuilder.Entity("Rewind.Models.Utilizadores", b =>
                {
                    b.Navigation("ListaDeComentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
